/*
   This file will be regenerated by `mulle-sde update|monitor`.
   Edits will be lost. Suppress this file with:

   mulle-sde environment set MULLE_SOURCETREE_TO_C_INCLUDE_FILE DISABLE
*/

#ifndef _glfwlatency_include_h__
#define _glfwlatency_include_h__

// remove with `mulle-sourcetree mark glfw no-header`
// rename with `mulle-sourcetree mark glfw set include whatever.h`
# include <GLFW/glfw3.h>   // glfw

#endif
